

@url = tfgrid.reservation.container.1
#links to unique node on the TFGrid
nodeid = (I)
flist = (S)
hub_url = (S)
#env variables
environment = (dict)
#the process to start
entrypoint = (S)
#corex yes or no
interactive = true (B)
volumes = (LO) !tfgrid.reservation.container.mount.1
network = (O) !tfgrid.reservation.network.1


@url = tfgrid.reservation.container.mount.1
volume_id = (S)
mountpoint = (S)

@url = tfgrid.reservation.network.1
network_id = (S)

