@url = calendar.1
version = "" (S)
title = "" (S)
description = "" (S)
events = (LO) !calendar.event.1


@url = calendar.event.1
id = ""
participants = (LO) !contact.1
alarm = !calendar.alarm.1
organizer= !contact.1 
start_time="" (D)
end_time="" (D)
summary = "" (S)
description = "" (S)
location="" (LF) #GPS coordinates 
status="confirmed,tentative,cancelled" (E) !
sequence="" (I)
category=  (LO)


@url = calendar.alarm.1
trigger = "-PT1440M"
action = "DISPLAY,AUDIO," (E)
repeat = "4" (I)
duration = "PT0H15M0S" (S) #Positive time x hours y minutes z seconds
description = "Reminder" (S)
