
@url = threebot.calendar.user.1
user_id** = (S)



@url = threebot.calendar.attachment.1
name** = (S)
content = (S)
encoding = (S)  #binary, base64


@url = threebot.calendar.event.1
item_id** = (S)
user_id** = (S)
calendar_id** = (S)
content = (S)
epoch = (T)
dtstart** = (T)
dtend** = (T)
type = (S)
timezone = (S)
title** = (S)
description** = (S)
location** = (S)
attachments = (LO) !threebot.calendar.attachment.1


@url = threebot.calendar.email.1
email** = (S)
type = (S) # work, etc

@url = threebot.calendar.telephone.1
telephone** = (S)
type = (S) # work, etc

@url = threebot.calendar.instantmessaging.1
username = (S)
type = (S)

@url = threebot.calendar.job.1
manager = (S)
profession = (S)
company = (S)
office = (S)
assistant = (S)
title = (S)
department = (S)
role = (S)

@url = threebot.calendar.mailaddress.1
street = (S)
city = (S)
code = (S)
region = (S) #state
country = (S)
box = (S)
extended = (S)
type = (S)

@url = threebot.calendar.certificate.1
type = (S) # pgp, x.509
text = (S)


@url = threebot.calendar.contact.1
item_id** = (S)
contact_id** = (S)
user_id** = (S)
addressbook_id** = (S)
content = (S)
epoch = (T)
type = (S)
title** = (S)
givenname** = (S)
familyname** = (S)
categories = (LS)
nickname = (S)
emails = (LO) !threebot.calendar.email.1
telephones = (LO) !threebot.calendar.telephone.1
ims = (LO) !threebot.calendar.instantmessaging.1
certificates = (LO) !threebot.calendar.certificate.1
mailaddresses = (LO) !threebot.calendar.mailaddress.1
job = (O) !threebot.calendar.job.1
anniversary = (T)
birthday = (T)
spouse = (S)
notes = (S)
picture = (O) !threebot.calendar.attachment.1
calendar_url = (S)
facebook  = (S)
homepage = (S)
blog = (S)
videchat = (S)

@url = threebot.calendar.calendar.1
calendar_id** = (S)
user_id** = (S)
props = (S)
cache = (S)
items = (LO) !threebot.calendar.event.1
type = "calendar" (S)
display_name = (S)
description = (S)
color = (S)

@url = threebot.calendar.addressbook.1
addressbook_id** = (S)
user_id** = (S)
props = (S)
cache = (S)
items = (LO) !threebot.calendar.contact.1
type = "addressbook" (S)
display_name = (S)
description = (S)
color = (S)
