
@url = tf.caldav.user.1
user_id** = (S)



@url = tf.caldav.attachment.1
name** = (S)
content = (S)
encoding = (S)


@url = tf.caldav.event.1
item_id** = (S)
user_id** = (S)
calendar_id** = (S)
content = (S)
epoch = (T)
dtstart = (T)
dtend = (T)
type = (S)
timezone = (S)
title = (S)
description = (S)
location = (S)
attachments = (LO) !tf.caldav.attachment.1


@url = tf.caldav.contact.1
item_id** = (S)
user_id** = (S)
addressbook_id** = (S)
content = (S)
epoch = (T)
type = (S)


@url = tf.caldav.calendar.1
calendar_id** = (S)
user_id** = (S)
props = (S)
cache = (S)
items = (LO) !tf.caldav.event.1
type = "calendar" (S)
display_name = (S)
description = (S)
color = (S)

@url = tf.caldav.addressbook.1
addressbook_id** = (S)
user_id** = (S)
props = (S)
cache = (S)
items = (LO) !tf.caldav.contact.1
type = "addressbook" (S)
display_name = (S)
description = (S)
color = (S)
