@url = threebot.registry.entry.1
@acl = false
url** = ""                              #unique url
tid_author = (I)
#e.g. https://www.mapdevelopers.com/geocode_tool.php
location_latitude** = (F)
location_longitude** = (F)
#see https://www.unece.org/cefact/locode/service/location.html
country_code** = ""
format** = "website,blog,wiki,doc,solutionpackage,threebotpackage" (E)
category** = "travel,food,it,spirituality,health,education,finance,varia" (E)
description = ""
signature = ""                          #proof that content is ok, is on fields aggregated in order
