@url = threebot.registry.entry.1
@acl = false
signature_hex = ""  #see phonebook, signature is on data for threebot.registry.entry.data.1 (capnp)
data = (BIN) #is the capnp format of !threebot.registry.entry.data.1

@url = threebot.registry.entry.data.1
authors = (LI)  #list of tid's, the authors can modify/delete info
readers = (LI)  #list of tid's, only relevant when encrypted, the readers can decrypt using their private key
registered_info = b""   #THIS CAN BE ENCRYPTED
registered_info_format = "jsxschema,yaml,json,msgpack,unstructured" (E)  #default jsxschema
registered_info_encrypted = (LO) !threebot.registry.entry.data_encrypted.1
schema_url = ""  #jumpscale schema url
#e.g. https://www.mapdevelopers.com/geocode_tool.php
location_latitude** = (F)
location_longitude** = (F)
#see https://www.unece.org/cefact/locode/service/location.html
country_code** = ""
format** = "website,blog,wiki,doc,solutionpackage,threebotpackage" (E)
category** = "publicity,info,knowledge,code,spec,config,varia" (E)
topic** = "travel,food,it,spirituality,health,education,finance,varia" (E)
description*** = ""


@url = threebot.registry.entry.data_encrypted.1
tid = 0 (I)
data = (BIN)  #or Binary?, what is type for binary


