@url = threebot.initialize.user.1
@acl = false
bot_name** = ""
public_key** = ""
referrer** = ""
location = (O) !threebot.initialize.user.location.1
wallet_keys = (LO) !threebot.initialize.user.wallet.1

@url = threebot.initialize.user.location.1
country = ""

@url = threebot.initialize.user.wallet.1
public_key = ""
secret_key = ""
