@url = user.1
@acl = false
bot_name** = ""
public_key** = ""
referrer** = ""
location = (O) !user.location.1
wallet_keys = (LO) !user.wallet.1

@url = user.location.1
country = ""

@url = user.wallet.1
public_key = ""
secret_key = ""