@url = jumpscale.fruum.user
anonymous** = (B)
admin** = (B)
blocked** = (B)
username** = (S)
displayname** = (S)
email = (S)
avatar = (S)
created = (S)
last_login = (S)
last_logout** = (S)
onboard = (S)
karma** = 0 (I)
logout_karma** = 0 (I)


@url = jumpscale.fruum.application
name** = (S)
description** = (S)
url = (S)
fullpage_url = (S)
pushstate** = (B)
theme = (S)
created = (S)
private_key = (S)
notifications_email = (S)
contact_email = (S)

@url = jumpscale.fruum.attachment
name** = (S)
type = (S) # image
data = (S) # base64

@url = jumpscale.fruum.document
doc_id** = (S)
app_name** = (S)
breadcrumb = (LS)
parent** = (S)
parent_type = (S)
type = "category" (S)
created = (S)
updated = (S)
initials = (S)
header** = (S)
body** = (S)
thumbnail = (S)
sticky** = (B)
locked** = (B)
visible** = True (B)
inappropriate** = (B)
permission** = 0 (I) # // 0: everyone, 1: logged-in, 2: admins
usage** = 0 (I)
user_id = (S)
user_username** = (S)
user_displayname** = (S)
user_avatar = (S)
order** = 0 (I)
react_up = (LS) # list of user names
react_down =  (LS) # List of user names
children_count** = 0 (I)
archived** = (B)
archived_ts** = 0 (I)
attachments = (LO) !jumpscale.fruum.attachment
tags = (LS)
