@url = tft.explorer.transaction.1
@acl = false
recipient** = ""
senders** = []
amount = ""
lock = 1568820802
message = b""
fee = false

@url = tft.explorer.wallet.1
@acl = false
address** = ""
last_activity_in = 1568820802
last_activity_out = 1568820802
balance_coins = tft.explorer.balance.1
balance_blockstakes = tft.explorer.balance.1
multisig_wallets = []


@url = tft.explorer.balance.1
@acl = false
liquid = 0
locked = 0

@url = tft.explorer.chain.1
@acl = false
name** = ""
balance_coins = tft.explorer.balance.1
balance_blockstakes = tft.explorer.balance.1
height = 0
timestamp = 0
