# snapshot of chain facts after applying the block
@url = threefold.tft_explorer.tft.explorer.block.facts.1
object_id = 0 (I)
target = "" (S)
difficulty = 0 (N)
aggregated_total_coins = 0 (N)
aggregated_total_coins_locked = 0 (N)
aggregated_total_block_stakes = 0 (N)
aggregated_total_block_stakes_locked = 0 (N)
aggregated_estimated_block_stakes_active = 0 (N)
