# used by the explorer to know at what part of the blockchain the DB syncing is
@url = threefold.tft_explorer.tft.explorer.chain.context.1
consensus_change_id = "" (S)
height = 0 (I)
timestamp = 0 (D)
block_id = "" (S)
