@url = threefold.tft_explorer.tft.explorer.contract.atomic.swap.1
object_id** = 0 (I)
value** = 0 (N)
condition = "" (S)
transaction_object_ids = (LI)
coin_input_object_id = (LI)
spenditure_data = (O) !threefold.tft_explorer.tft.explorer.contract.atomic.swap.spenditure.data.1

@url = threefold.tft_explorer.tft.explorer.contract.atomic.swap.spenditure.data.1
fulfillment = "" (S)
coin_output_object_id = 0 (I)
