@url = tft.explorer.wallet.1
address** = ""  (S)
last_activity_in = "" (D)
last_activity_out = "" (D)
balance_coins = !tft.explorer.balance.1
balance_blockstakes = !tft.explorer.balance.1
multisig_wallets = "1,2,3" (LS)

@url = tft.explorer.balance.1
liquid = "0" (F)
locked = "0" (F)

@url = tft.explorer.chain.1
name** = ""
balance_coins = !tft.explorer.balance.1
balance_blockstakes = !tft.explorer.balance.1
height = 0 (I)
timestamp = "" (D)