@url = threefold.tft_explorer.tft.explorer.transaction.1
object_id** = 0 (I)
parent_block_object_id = 0 (I)
version = 0 (I)
coin_input_object_ids = (LI)
coin_output_object_ids = (LI)
block_stake_input_object_ids = (LI)
block_stake_output_object_ids = (LI)
fee_payout = (O) !threefold.tft_explorer.tft.explorer.transaction.payout.fee.info.1
arbitrary_data = "" (S)
encoded_extension_data = "" (S)

@url = threefold.tft_explorer.tft.explorer.transaction.payout.fee.info.1
payout_output_object_id = 0 (I)
payout_values = (LN)
