@url = jumpscale.email.header
key = (S)
value = (S)

@url = jumpscale.email.attachement
name = (S)
content = (bin)
contenttype = (S)


@url = jumpscale.email.message
name** = ""
from_email = "" (S)
to_email = "" (S)
subject = "" (S)
headers = (LO)!jumpscale.email.header
attachments = (LO)!jumpscale.email.attachement
body = "" (S)
htmlbody = "" (S)