@url = jumpscale.ibiza.ibiza.1
jwt = "" (S)                # JWT Token
addr**= ""                   # Address
ipaddr = (ipaddr)           # IP Address
email = "" (S)              # Email address
username = "" (S)           # User name
