
@url = tfgrid.reservation.1

#json of the reservation.data object, will not change over time
json = "" (S)
data = (O) !tfgrid.reservation.data.1

#id of threebot which pays for it
customer_tid = (I)
#signature with private key of customer of the json, this guarantees that the data did not change
customer_signature = (S)

#state, allows anyone to see what can happen next e.g. sign means waiting for everyone to sign
#delete means its deployed now we need to wait till enough people sign to delete
next_action = "sign,pay,deploy,delete,invalid,deleted" (E)
signatures_provision = (LO) !tfgrid.reservation.signing.signature.1
signature_farmer = (LO) !tfgrid.reservation.signing.signature.1
signatures_delete = (LO) !tfgrid.reservation.signing.signature.1
epoch = (D)
results = (LO) !tfgrid.reservation.result.1

@url = tfgrid.reservation.data.1
#this one does not change over time
description = ""
containers = (LO) !tfgrid.reservation.container.1
volumes = (LO) !tfgrid.reservation.volume.1
zdbs = (LO) !tfgrid.reservation.zdb.1
networks = (LO) !tfgrid.reservation.network.1
#till whe is request for provisioning valid, if not signed in required time then obsolete
expiration_provisioning = (D)
#till whe is reservation valid
expiration_reservation = (D)
#need toget to consensus
signing_request_provision = (O) !tfgrid.reservation.signing.request.1
signing_request_delete = (O) !tfgrid.reservation.signing.request.1

@url = tfgrid.reservation.signing.request.1
#part of the reservation.data, because should never be possible to delete this
#threebotids of people who can sign
signers = (LI)
#min nr of people who need to sign
quorum_min = (I)

@url = tfgrid.reservation.signing.signature.1
#threebotid
tid = (I)
#isgnature in binary form of the json as stored in the root of this obj
signature (B)
#time of signature
epoch = (D)

