

@url = tfgrid.reservation.volume.1
#unique id inside the reservation is an autoincrement
workload_id = (I)
nodeid = (I)
reservation_id** =  (I)
size = (I)
type = "HDD,SSD" (E)
#where to send the statistics too
stats_aggregator = (LO) !tfgrid.reservation.statsaggregator.1
#id of threebot who is the farmer
farmer_tid = (I)

