@url = tfgrid.reservation.network.1
#unique id inside the reservation is an autoincrement (USE AS NET_ID)
workload_id = (I)
# original /48 allocation of the farm
prefix_zero = (iprange)
# each node part of the network has a network resource associated
resources = (LO) !tfgrid.network.net_resource.1
allocation_nr = (I)
version = (I)
#where to send the statistics too
stats_aggregator = (LO) !tfgrid.reservation.statsaggregator.1
#id of threebot who is the farmer
farmer_tid = (I)

@url = tfgrid.network.node_id.1
node_id = (S)
farm_id = (S)
reachability_v4 = "PUBLIC,HIDDEN" (E)
reachability_v6 = "PUBLIC,HIDDEN" (E)

#wireguard instance
@url = tfgrid.network.net_resource.1
node_id = (O) !tfgrid.network.node_id.1
prefix = (iprange)
#
exit_point = (I)
# wireguard private key. encrypted with the public key of the node
private_key = (S)
