@url = user.1
@acl = false
bot_name** = ""
public_key** = ""
referrer** = ""
location = (O) !user.location.1
threebot_keys = (LO) !user.threebot_keys.1
wallet_keys = (LO) !user.wallet_keys.1

@url = user.location.1
country = ""

@url = user.threebot_keys.1
public_key = ""
secret_key = ""

@url = user.wallet_keys.1
public_key = ""
secret_key = ""