@url = contact.people.1
@acl = false
firstname** =""
lastname** = ""
phone_numbers =  (LO) !contact.people.phone.1
addresses =  (LO) !contact.people.addresses.1
email = "" (LS)
picture= "" 
birthdate= ""
website=""
job_title=""
salutation = "Mr,Miss,Mme"
3bot_ids = "" (LI)

@url = contact.people.phone.1
@acl = false
number** = ""
extensions= ""
description= ""
priority= ""
type= ""

@url = contact.people.addresses.1
building_number = ""
street_number= ""
street_name** =""
area_locality= ""
city** = ""
zip_code= ""
state_province= ""
country** = ""
other_detail= ""