@url = contact.people.1
@acl = false
phone_numbers =  []
addresses =  []
emails = [] 
picture= "" 
birthdate= ""


@url = contact.people.phone.1
@acl = false
number = ""
extensions= ""
description= ""
priority= ""
type= ""