@url = threebot.blog.blog
name** = "" (S)
git_repo_url** = "" (S)
metadata = (O) !threebot.blog.metadata
posts =  (LO) !threebot.blog.post
pages = (LO) !threebot.blog.post

@url = threebot.blog.metadata
blog_name** = "" (S)
blog_title** = "JSX blog" (S)
blog_description = "JSX blog description" (S)
author_name = "" (S)
author_email = "" (S)
author_image = ""
base_url = "" (S)
url = "" (S)
posts_dir = "posts"
github_username = "" (S)
github_repo_url** = "" (S)
nav_links = (LO)      !threebot.blog.link
sidebar_social_links = (LO) !threebot.blog.link
sidebar_links = (LO)  !threebot.blog.link
allow_disqus = true (B)
allow_navbar = true (B)
allow_footer = true (B)
posts_per_page = (I)

@url = threebot.blog.post
title** = "" (S)
slug** = "" (S)
content = "" (S)
content_with_meta = "" (S)
tags = (LS)
published_at = "" (S)
author_name = "" (S)
author_email = "" (S)
author_image = "" (S)
post_image = "" (S)
excerpt = "" (S)
description = "" (S)

@url = threebot.blog.link
title** = "" (S)
link = "" (S)
page = "" (S)
faclass = "" (S)
