@url = jumpscale.fruum.user
anonymous** = (B)
admin** = (B)
blocked** = (B)
username** = (S)
displayname** = (S)
email = (S)
avatar = (S)
created** = (I)
last_login** = (I)
last_logout** = (I)
onboard** = (I)
karma** = (I)
logout_karma** = (I)


@url = jumpscale.fruum.application
app_id = (S)
name** = (S)
description** = (S)
url = (S)
auth_url = (S)
fullpage_url = (S)
pushstate** = (B)
theme = (S)
created** = (I)
private_key = (S)
notifications_email = (S)
contact_email = (S)


@url = jumpscale.fruum.document
breadcrumb = L(S)
parent = (S)
parent_type = (S)
type = (S)
created** = (I)
updated** = (I)
initials = (S)
header** = (S)
body** = (S)
thumbnail = (S)
sticky** = (B)
locked** = (B)
visible** = (B)
inappropriate** = (B)
permission** = (I) # // 0: everyone, 1: logged-in, 2: admins
usage** = (I)
user_id = (S)
user_username** = (S)
user_displayname** = (S)
user_avatar = (S)
order** = (I)
react_up = L(S) # list of user names
react_down =  L(S) # List of user names
children_count** = (I)
archived** = (B)
archived_ts** = (I)
tags = L(S)
