@url = threebot.mail.email.attachement.1
name = (S)
content = (bin)
contenttype = (S)

@url = threebot.mail.email.message.1
from_email = "" (S)
to_email = "" (S)
subject = "" (S)
attachments = (LO)!threebot.mail.email.attachement.1
body = "" (S)
htmlbody = "" (S)
date** = (T)
priority = (B)
headers = "" (S)
