@url = jumpscale.email.message
name** = ""
from_email = "" (S)
to_email = "" (S)
subject = "" (S)
folder = "" (S)
headers = (LO)!jumpscale.email.header
attachments = (LO)!jumpscale.email.attachement
body = "" (S)
htmlbody = "" (S)
