

@url = tfgrid.workloads.reservation.container.1
#unique id inside the reservation is an autoincrement
0 : workload_id = (I)
#links to unique node on the TFGrid
1 : node_id = (S)
2 : flist = (S)
3 : hub_url = (S)
#env variables
4 : environment = (dict)
#secret_env variables. the key is in plain text but the value
#must be encrypted using Curve25519 with the public key of node.
#then hex encoded.
5 : secret_environment = (dict)
#the process to start
6 : entrypoint = (S)
#corex yes or no
7 : interactive = true (B)
8 : volumes = (LO) !tfgrid.workloads.reservation.container.mount.1
9 : network_connection = (LO) !tfgrid.workloads.reservation.network.connection.1
#where to send the statistics too
10 : stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
#id of threebot who is the farmer
11 : farmer_tid = (I)
12 : capacity = (O) !tfgrid.workloads.reservation.container.capacity.1



@url = tfgrid.workloads.reservation.container.mount.1
0 : volume_id = (S)
1 : mountpoint = (S)

@url = tfgrid.workloads.reservation.network.connection.1
0 : network_id = (S)
1 : ipaddress = (ipaddress)
2 : public_ip6 = (B)

@url = tfgrid.workloads.reservation.container.capacity.1
# Number of vCPU
0 : cpu = (I) 
# memory in MiB
1 : memory = (I)
