@url = tfgrid.workloads.reservation.k8s.1
#unique id inside the reservation is an autoincrement
0 : workload_id = (I)
#links to unique node on the TFGrid
1 : node_id = (S)
# defines the amount of vCpu, memory, and the disk size
# size 1: 1 vCpu, 2 GiB RAM, 50 GB disk
# size 2: 2 vCpu, 4 GiB RAM, 100 GB disk
2 : size = (I)
3 : network_id = (S)
4 : ipaddress = (ipaddress)
# ClusterSecret is the hex encoded encrypted cluster secret
5 : cluster_secret = (S)
# master_ips define the URL's for the kubernetes master nodes. If this
# list is empty, this node is considered to be a master node.
6 : master_ips = (Lipaddress)
# list of public ssh keys to add to the VM
7 : ssh_keys = (LS)
#where to send the statistics too
8 : stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
#id of threebot who is the farmer
9 : farmer_tid = (I)