

@url = tfgrid.workloads.reservation.volume.1
#unique id inside the reservation is an autoincrement
0 : workload_id = (I)
1 : node_id = (S)
2 : size = (I)
3 : type = "HDD,SSD" (E)
#where to send the statistics too
4 : stats_aggregator = (LO) !tfgrid.workloads.reservation.statsaggregator.1
#id of threebot who is the farmer
5 : farmer_tid = (I)
