@url = tfgrid.workloads.reservation.workload.1
0 : workload_id = (S)
1 : user = (S)
2 : type = "zdb,container,volume,network,kubernetes" (E)
3 : content = (dict)
4 : created = (T)
5 : duration = (I)
6 : signature = (S)
7 : to_delete = (B)
